### ISSUE TITLE
If CAVOK = True then Temperature Dewpoint and Altimeter are not read

### ISSUE THREAD

**Issue by Wamwod** [larrrssss/metar-decoder#4]
Title any time Cavok is true it doesn't read any of the data in the Title. Ex. with CAVOK = True
`{
  rvr: [],
  clouds: [],
  weather: [],
  auto: false,
  cavok: true,
  visibility: 9999,
  airport: 'UGKO',
  recorded_at: 2022-07-08T00:30:00.000Z,
  wind: { direction: '070', speed: 3, guest: null, unit: 'KT' },
  fetchAirport: [Function (anonymous)]
}`
And an example with .replace('Cavok, '9999')
`{
  rvr: [],
  clouds: [],
  weather: [],
  auto: false,
  cavok: false,
  airport: 'UGKO',
  recorded_at: 2022-07-08T00:30:00.000Z,
  wind: { direction: '070', speed: 3, guest: null, unit: 'KT' },
  visibility: 9999,
  dewpoint: 18,
  temperature: 18,
  qnh: 1009,
  trend: { type: 'No significant change', full: 'NOSIG' },      
  fetchAirport: [Function (anonymous)]
}`

**Comment by larrrssss** [comment]
hey @Wamwod 👋🏼 

thank you for your issue. 

could you send me the full METAR you tried to decode?

**Comment by Wamwod** [comment]
This one has the issue  `UGKO 091330Z 25012KT CAVOK 28/20 Q1005 NOSIG`  I've had to run `.replace('CAVOK', '9999')`; before i parse it to get the rest of the data for now. Not the metar I was decoding but it has the same issue

**Comment by larrrssss** [comment]
should be fixed in v. 1.0.3
